import "bootstrap/dist/css/bootstrap.min.css"
import { fetchShelvesWithBooksId } from "../src/books/actions";
import { Shelves } from "../src/shelves/components/shelves";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const shelves = await fetchShelvesWithBooksId();
  return (
    <html lang="en">
      <body>
        <div>
          <nav className="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
            <a className="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Bibliothèque</a>
            <input className="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search" />
            <ul className="navbar-nav px-3">
              <li className="nav-item text-nowrap">
                <a className="nav-link" href="#">Rechercher</a>
              </li>
            </ul>
          </nav>
          <div className="container-fluid">
            <div className="row">
              <Shelves shelves={shelves} />
              <main role="main" className="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
                {children}
              </main>
            </div>
          </div>
        </div>
      </body>
    </html>
  )
}
